config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  # Using devise with multiple models : https://github.com/plataformatec/devise/wiki/How-to-Setup-Multiple-Devise-User-Models
  devise_for :doctors, controllers: { sessions: 'doctors/sessions',
                                      registrations: 'doctors/registrations' }
  devise_for :pharmacists, controllers: { sessions: 'pharmacists/sessions',
                                          registrations: 'pharmacists/registrations' }
  devise_for :admins, controllers: { sessions: 'admins/sessions',
                                      registrations: 'admins/registrations' }
  devise_for :users, controllers: { sessions: 'users/sessions' }

  namespace :pharmacists do
    get 'accueil', to: 'pages#index'
    get 'patient/nouveau', to: 'users#new'
    post 'patients', to: 'users#create'
    get 'patients/:id/editer', to: 'users#edit'
    post 'patients/:id/mettre_a_jour', to: 'users#update'
    get 'ordonnance/nouvelle', to: 'prescriptions#new'
    post 'ordonnances', to: 'prescriptions#create'
    get 'ordonnances/:id/editer', to: 'prescriptions#edit'
    post 'ordonnances/:id/mettre_a_jour', to: 'prescriptions#update'
  end

  namespace :admins do
    get 'accueil', to: 'pages#index'
  end

  root to: 'pages#index'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Telemed</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to '#', class: 'nav-link' do %>
        <%= @nav %> <span class="sr-only">(current)</span>
      <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Aide
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <%= link_to 'Administration', new_admin_session_path, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
    <!--   We can use one link to kill the session of each user model. See. config.sign_out_all_scopes = true -->
    <% if user_signed_in? || doctor_signed_in? || pharmacist_signed_in? || admin_signed_in? %>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger my-2 my-sm-0'%>
      </form>
    <% end %>
  </div>
</nav>